export const pcListe = [
    {
        id:1,
        hersteller:"fujitsu",
        geraetenummer:"PC.23.03.09.01",
        prozessor:"Intel Core i3-4130 - 3,4 GHz",
        betriebssystem:"Ubuntu 20.4.01",
        ram :" 2*4 GB DDR 3",
        festplatte:{typ:"ssd", size:"500"},
        benchmark:"geek 993",
        funktion:"getestet",
        benutzername:"user",
        passwort:"user",
        aufLager:true,
        endkontrolle:"datum 16.03.23",
    },
    {
        id:2,
        hersteller:"fujitsu",
        geraetenummer:"PC.24.02.09.01",
        prozessor:"Intel Core i5-4130 - 3,4 GHz",
        betriebssystem:"Ubuntu 20.4.01",
        ram :" 1*4 GB DDR 3",
        festplatte:{typ:"hdd", size:"150"},
        benchmark:"geek 600",
        funktion:"getestet",
        benutzername:"user",
        passwort:"user",
        aufLager:true,
        endkontrolle:"datum 16.03.2024",
    },
    {
        id:3,
        hersteller:"hp",
        geraetenummer:"PC.23.05.09.01",
        prozessor:"Intel Core i9-4130 - 3,4 GHz",
        betriebssystem:"Ubuntu 20.4.01",
        ram :" 2*4 GB DDR 3",
        festplatte:{typ:"HDD", size:"500"},
        benchmark:"geek 1258",
        funktion:"getestet",
        benutzername:"user",
        passwort:"user",
        aufLager:false,
        endkontrolle:"datum 16.02.2024",
    },
    {
        id:4,
        hersteller:"medion",
        geraetenummer:"PC.23.02.11.01",
        prozessor:"Intel Core i5-4130 - 3,4 GHz",
        betriebssystem:"Ubuntu 20.4.01",
        ram :" 2*4 GB DDR 3",
        festplatte:{typ:"ssd", size:"500"},
        benchmark:"geek 993",
        funktion:"getestet",
        benutzername:"user",
        passwort:"user",
        aufLager:false,
        endkontrolle:"datum 13.01.2024",
    },
]